apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: terrafusion
data:
  DB_HOST: "terrafusion-mysql.xxxxxxxxxx.ap-south-1.rds.amazonaws.com"
  DB_PORT: "3306"
  DB_NAME: "terrafusion"
  DB_USER: "terrafusion_admin"
  DB_TYPE: "mysql"
  NODE_ENV: "production"
